Algoritmo "Exercício_I"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Exercicio_i.
// Autor(a)    : kaua oraboni
// Data atual  : 16/04/2024
Var
   num:inteiro

Inicio
   escreval ("digite um numero")
   leia (num)
   se num mod 2 = 0 entao
      Escreval("O número ", num, " é par.")
   senao
      Escreval("O número ", num, " é ímpar.")
   fimse
FimAlgoritmo
