Algoritmo "Exercicio_a"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : kaua oraboni
// Data atual  : 15/04/2024
Var

   numero:inteiro

Inicio

     numero <- 15
   repita
      Escreval(numero * numero)
      numero <- numero + 1
   ate numero > 200

Fimalgoritmo