Algoritmo "EXERCICIO_C"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : kaua oraboni
// Data atual  : 15/04/2024
Var
   numero: inteiro

Inicio
   numero <- 1
   repita
      se numero % 4 = 0 entao
         escreval (numero)
      fimse
      numero <- numero + 1
   ate numero > 200
Fimalgoritmo