Algoritmo "Exercício_J"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Exercicio_j.
// Autor(a)    : kaua oraboni
// Data atual  : 14/04/2024
Var
quantidadeDolar:real
IC:real
valor :real
Inicio
escreval ("insira a quantidade de dolares")
leia (quantidadeDolar)
escreval ("qual o valor da cotação do dolar hoje")
leia (IC)
valor <- (quantidadeDolar * IC)
escreval ("O valor da transformação é R$:", valor)

Fimalgoritmo
