Algoritmo "EXERCICIO_E"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : kaua oraboni
// Data atual  : 16/04/2024
Var
   contadora:inteiro

Inicio
   para contadora de 1 ate 20 passo 1 faca
      se contadora % 2 = 1 entao
         escreval ("Números ímpares de 1 até 20:", contadora)
      fimse
   fimpara
Fimalgoritmo