Algoritmo "EXERCICIO_F"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : kaua oraboni
// Data atual  : 16/04/2024
Var
   contadora:inteiro

Inicio
   para contadora de 1 ate 200 passo 1 faca
      se contadora % 4 = 0 entao
         escreval (contadora)
      fimse
   fimpara
Fimalgoritmo