Algoritmo "EXERCICIO_A"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : kaua oraboni
// Data atual  : 16/04/2024
Var
contadora,resultado:inteiro

Inicio
   para contadora de 15 ate 200 passo 1 faca
      resultado <- contadora * contadora
      escreval(contadora, " ^ 2 =", resultado)
   fimpara
Fimalgoritmo